/**
 * Dashboard generator — regenerate library/README.md from DB data.
 */

import { Database } from '@db/sqlite';
import { join } from '@std/path';

/**
 * Regenerate the library README.md dashboard from DB data.
 */
export async function regenerateDashboard(db: Database, libraryPath: string): Promise<void> {
  // Query stats
  const sessionCount = (
    db.prepare('SELECT COUNT(*) as c FROM sessions').get() as { c: number }
  ).c;

  const modeCounts = db
    .prepare('SELECT mode, COUNT(*) as c FROM sessions GROUP BY mode ORDER BY c DESC')
    .all() as Array<{ mode: string; c: number }>;

  const snippetCount = (
    db.prepare("SELECT COUNT(*) as c FROM items WHERE type = 'snippet'").get() as { c: number }
  ).c;

  const tldrCount = (
    db.prepare("SELECT COUNT(*) as c FROM items WHERE type = 'tldr'").get() as { c: number }
  ).c;

  const projectCount = (
    db.prepare("SELECT COUNT(*) as c FROM items WHERE type = 'project'").get() as { c: number }
  ).c;

  // Recent snippets
  const recentSnippets = db
    .prepare("SELECT title, path FROM items WHERE type = 'snippet' ORDER BY created DESC LIMIT 5")
    .all() as Array<{ title: string; path: string }>;

  // TLDRs
  const tldrs = db
    .prepare("SELECT title, path FROM items WHERE type = 'tldr' ORDER BY created DESC")
    .all() as Array<{ title: string; path: string }>;

  // Projects
  const projects = db
    .prepare("SELECT title, path FROM items WHERE type = 'project' ORDER BY created DESC")
    .all() as Array<{ title: string; path: string }>;

  // Build README
  let md = `# 🎓 Dev Coach — My Knowledge Base\n\n`;

  // Stats
  md += `## 📊 Stats\n`;
  md += `- Total sessions: ${sessionCount}`;
  if (modeCounts.length > 0) {
    md += ` (${modeCounts.map((m) => `${m.mode}: ${m.c}`).join(', ')})`;
  }
  md += `\n`;
  md += `- Snippets: ${snippetCount} | TLDRs: ${tldrCount} | Projects: ${projectCount}\n\n`;

  // Recent snippets
  md += `## 📝 Recent Snippets\n`;
  if (recentSnippets.length === 0) {
    md += `_No snippets yet. Try \`coach sandbox "topic"\` to start collecting!_\n\n`;
  } else {
    for (const s of recentSnippets) {
      md += `- [${s.title}](${s.path})\n`;
    }
    md += `\n`;
  }

  // TLDRs
  md += `## 📖 TLDRs\n`;
  if (tldrs.length === 0) {
    md += `_No TLDRs yet. Try \`coach ask "question"\` and save the answer!_\n\n`;
  } else {
    for (const t of tldrs) {
      md += `- [${t.title}](${t.path})\n`;
    }
    md += `\n`;
  }

  // Projects
  md += `## 🏗️ Projects\n`;
  if (projects.length === 0) {
    md += `_No projects yet. Try \`coach project "idea"\` to build something!_\n\n`;
  } else {
    for (const p of projects) {
      md += `- [${p.title}](${p.path})\n`;
    }
    md += `\n`;
  }

  md += `---\n_Generated by Dev Coach. Updated automatically._\n`;

  await Deno.writeTextFile(join(libraryPath, 'README.md'), md);
}
